[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = [ 'markdown', 'pandoc.markdown', 'rmd' ]
build = 'sh -c "cd app & yarn install" '
hook_add = '''
nnoremap <Leader>md :MarkdownPreviewToggle<cr>
'''
